name = "lean4-tutorial"
version = "0.1.0"
defaultTargets = ["grader"]

[leanOptions]
relaxedAutoImplicit = false

[[lean_lib]]
name = "SoftwareFoundations"

[[lean_lib]]
name = "Book"

[[lean_exe]]
name = "grader"
root = "Main"
